# Generated by Django 3.1.1 on 2022-04-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('customer_gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], null=True)),
                ('customer_marital_status', models.TextField(null=True)),
                ('customer_income_from_range', models.TextField(null=True)),
                ('customer_income_to_range', models.IntegerField(null=True)),
                ('customer_region', models.TextField(null=True)),
            ],
        ),
    ]
