# Generated by Django 3.1.1 on 2022-04-16 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20220416_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.IntegerField(unique=True)),
                ('premium', models.IntegerField(null=True)),
                ('fuel', models.TextField(null=True)),
                ('vehical_segment', models.TextField(null=True)),
                ('bodily_injury_libility', models.IntegerField(null=True)),
                ('bodily_damage_libility', models.IntegerField(null=True)),
                ('personal_injury_protection', models.IntegerField(null=True)),
                ('collision', models.IntegerField(null=True)),
                ('comprehensive', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
